version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1

    working_directory: /go/src/github.com/moomerman/pipeline
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
