version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1

    working_directory: /go/src/github.com/moomerman/pipeline
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: go get -v -t -d ./...
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            go test -coverprofile c.out -v ./...
            ./cc-test-reporter after-build --exit-code $?
